coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto
        branches:
          - main
          - develop
    patch:
      default:
        target: 60%
        threshold: 1%
        base: auto

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

github_checks:
  annotations: true

flags:
  server:
    paths:
      - server/
    carryforward: true

# Ignore patterns for coverage (optional - uncomment if needed)
# ignore:
#   - "server/src/**/*.spec.ts"
#   - "server/src/**/*.e2e.spec.ts"
#   - "server/src/**/*.integration.spec.ts"

