apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iitd-server-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # TODO: Update this URL to match your GitHub repository
    # Example: repoURL: https://github.com/YOUR_USERNAME/iitd.git
    repoURL: https://github.com/your-org/iitd.git
    targetRevision: develop
    path: infra/k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: iitd-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

